server:
  port: 8080

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/stu_info
    username: root
    password: Azhar@9103s
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis